"""add loan score_at_decision and policy_min_score_at_decision

Revision ID: 121ba659e2ce
Revises: 92d46b3ac42a
Create Date: 2026-08-02 04:39:22.308909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '121ba659e2ce'
down_revision: Union[str, None] = '92d46b3ac42a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('score_at_decision', sa.Numeric(precision=6, scale=2), nullable=False))
    op.add_column('loans', sa.Column('policy_min_score_at_decision', sa.Numeric(precision=6, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'policy_min_score_at_decision')
    op.drop_column('loans', 'score_at_decision')
    # ### end Alembic commands ###
