"""update lender platform cap and loan lender_id

Revision ID: 5310023e0c06
Revises: 7f77c36186ae
Create Date: 2026-08-01 23:52:48.639737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5310023e0c06'
down_revision: Union[str, None] = '7f77c36186ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
