"""add agent api_key hash

Revision ID: 55adca992bb4
Revises: 5cd7355d9be2
Create Date: 2026-08-12 17:15:50.307661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55adca992bb4'
down_revision: Union[str, None] = '5cd7355d9be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('api_key_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'api_key_hash')
    # ### end Alembic commands ###
