"""add insurance pool, loan/event fields, transaction types

Revision ID: 57c8f6008920
Revises: 121ba659e2ce
Create Date: 2026-08-02 08:06:18.499742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57c8f6008920'
down_revision: Union[str, None] = '121ba659e2ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("INSERT INTO insurance_pool (id, balance) VALUES (1, 0)")
    # ### end Alembic commands ###s


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insurance_pool')
    # ### end Alembic commands ###
