"""add lender platform cap and loan lender_id

Revision ID: 7f77c36186ae
Revises: f6964da3a20b
Create Date: 2026-08-01 23:46:55.430398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f77c36186ae'
down_revision: Union[str, None] = 'f6964da3a20b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lenders', sa.Column('total_platform_exposure_cap', sa.Numeric(precision=18, scale=2), nullable=False))
    op.add_column('loans', sa.Column('lender_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'loans', 'lenders', ['lender_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.drop_column('loans', 'lender_id')
    op.drop_column('lenders', 'total_platform_exposure_cap')
    # ### end Alembic commands ###
