"""add manual_credit_limit_override to agents

Revision ID: 8dc3292d50a6
Revises: 57c8f6008920
Create Date: 2026-08-02 12:04:28.118171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dc3292d50a6'
down_revision: Union[str, None] = '57c8f6008920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('manual_credit_limit_override', sa.Numeric(precision=18, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'manual_credit_limit_override')
    # ### end Alembic commands ###
