"""add loan approved_recipient and event loan_id

Revision ID: 92d46b3ac42a
Revises: 5310023e0c06
Create Date: 2026-08-02 03:45:21.781812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d46b3ac42a'
down_revision: Union[str, None] = '5310023e0c06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('vouching_enabled', sa.Boolean(), nullable=False))
    op.add_column('events', sa.Column('loan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'loans', ['loan_id'], ['id'])
    op.add_column('lenders', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('lenders', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'lenders', ['email'])
    op.add_column('loans', sa.Column('interest_amount', sa.Numeric(precision=18, scale=2), nullable=False))
    op.add_column('loans', sa.Column('write_off_amount', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('loans', sa.Column('approved_recipient', sa.String(length=255), nullable=False))
    op.add_column('principals', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('principals', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'principals', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'principals', type_='unique')
    op.drop_column('principals', 'hashed_password')
    op.drop_column('principals', 'email')
    op.drop_column('loans', 'approved_recipient')
    op.drop_column('loans', 'write_off_amount')
    op.drop_column('loans', 'interest_amount')
    op.drop_constraint(None, 'lenders', type_='unique')
    op.drop_column('lenders', 'hashed_password')
    op.drop_column('lenders', 'email')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'loan_id')
    op.drop_column('agents', 'vouching_enabled')
    # ### end Alembic commands ###
